Microverse 1st capstone,Thopic: The vitron community
camilevahviraki/Capstone_first pull request #1
Opened 2022-04-14 13:11 UTC by camilevahviraki

### **In this milestone we: **

- [ ] Added the `Index.html` file which contains all the sections pages.
- [ ] Added the `index.css` file to style the capstone.
- [ ] Added the `index.js` file to improve some dynamism to the page.
- [ ] Added images folder to the repo.
- [ ] Added cocogoose custom font-family to the repo.

2022-04-15 15:33 UTC, gemmen29 requested changes
Hi @camilevahviraki, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 15:33 UTC, gemmen29 commented on index.html
> +        <h1 class="big_title">THE VITRON COMMUNITY SAYS HELLO.</h1>
- [ ] Kindly decrease the font size of this heading in the mobile version `home` page to match the Behance design and to get rid of the general scrolling problem.

| Your design | Behance design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/163586744-ad3dfe54-0071-4af8-af43-ba0504ea30b7.png) | ![image](https://user-images.githubusercontent.com/24703171/163586378-59e8241c-79a0-4916-8582-d76f7060ab8a.png) |

2022-04-15 15:33 UTC, gemmen29 commented on index.html
> +        <h3 class="adresse">@The Liberty Warehouse,Red Hook,Brooklyn.</h3>
- [ ] Kindly adjust this part to be more to the left to match the Behance design.

| Your design | Behance design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/163587391-66891bac-a4ad-4383-aec6-a060be388d29.png) | ![image](https://user-images.githubusercontent.com/24703171/163587651-c9ffa462-dcd0-45da-9a35-3fe76b995e85.png) |

2022-04-15 15:33 UTC, gemmen29 commented on index.html
> +          </div>
Kindly increase the spacing between `h3` and `p` to match the Behance design.

| Your design | Behance design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/163587957-81991da1-f38f-4f57-b90f-ac25fd4f07d7.png) | ![image](https://user-images.githubusercontent.com/24703171/163587871-30e4dc6d-953b-4c41-ac6d-a31479237814.png) |

2022-04-15 15:33 UTC, gemmen29 commented on index.html
> +        </ul>
- [ ] Kindly make the mobile menu take the full height of the page and stop scrolling when the menu opens for a better UI experience.

2022-04-15 15:33 UTC, gemmen29 commented on README.md
> +
- [ ] Kindly add an acknowledgment to [Cindy Shin](https://www.behance.net/adagio07) the author of the original design as required by the Creative Commons License in your README file.

2022-04-15 15:33 UTC, gemmen29 commented on index.html
> +        <h1 class="big_title">THE VITRON COMMUNITY SAYS HELLO.</h1>
- [ ] Kindly decrease the font size of this heading in the mobile version `about` page and make it in the center to match the Behance design and to get rid of the general scrolling problem.

| Your design | Behance design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/163586744-ad3dfe54-0071-4af8-af43-ba0504ea30b7.png) | ![image](https://user-images.githubusercontent.com/24703171/163586378-59e8241c-79a0-4916-8582-d76f7060ab8a.png) |
 
![image](https://user-images.githubusercontent.com/24703171/163589369-caca1614-5a13-4e35-891d-199058a63bd2.png)

2022-04-15 15:33 UTC, gemmen29 commented on index.html
> +        </div>
- [ ] Kindly make these paragraphs displayed properly so all words appear and decrease the spacing between year and paragraph to match the Behance design.

| Your design | Behance design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/163589841-050ee892-e6d0-44cd-87e9-f72a0354ffae.png) | ![image](https://user-images.githubusercontent.com/24703171/163590156-2ea15d2e-6475-4b73-9206-7145ae585aa9.png) |

2022-04-15 17:18 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @camilevahviraki , 

Great work on making the changes 👏 
In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
Good luck! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 17:21 UTC, merged

2022-12-12 09:44 UTC, camilevahviraki commented
Thanks

2023-03-03 16:29 UTC, camilevahviraki commented
### Hi there:wave:
I have updated the app and made it Clean and Dry in [this pull request](https://github.com/camilevahviraki/Capstone_first/pull/2), and [the live demo](https://capstone-first-vitron-events.netlify.app/)